---
title: "HW3"
author: "Ziyu Liu"
date: "2024-03-24"
output: html_document
---

```{r, warning=FALSE, message=FALSE}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
```

## Load packages
```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggplot2)
library(Tweedieverse) # devtools::install_github('himelmallick/Tweedieverse')
library(scran) 
library(SC2P) 
library(boost) 
library(SPARK) 
library(spatialDE)
library(Seurat)
library(utils)
library(stats)
library(grDevices)
library(mgcv)
library(DESeq2)
library(edgeR)
library(gplots)
library(nnSVG)
library(SeuratData)
library(SpatialExperiment)
library(glmGamPoi)
theme_set(theme_bw())
```


## Seurat tutorial
```{r}
# Load the PBMC dataset
pbmc.data <- Read10X(data.dir = "filtered_gene_bc_matrices/hg19/")
# Initialize the Seurat object with the raw (non-normalized data).
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
pbmc

pbmc[[]]
```

```{r, fig.width=10}
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")
VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r, fig.width=10}
plot1 <- FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2

pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)
```

```{r}
pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)
```

```{r, fig.width=10}
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(pbmc), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(pbmc)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
plot1 + plot2
```


```{r}
all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)
```


```{r}
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
```


```{r}
# Examine and visualize PCA results a few different ways
print(pbmc[["pca"]], dims = 1:5, nfeatures = 5)
```


```{r, fig.width=10}
VizDimLoadings(pbmc, dims = 1:2, reduction = "pca")
```


```{r}
DimPlot(pbmc, reduction = "pca") + NoLegend()
```


```{r}
DimHeatmap(pbmc, dims = 1, cells = 500, balanced = TRUE)
```

```{r, fig.height=20, fig.width=15}
DimHeatmap(pbmc, dims = 1:15, cells = 500, balanced = TRUE)
```

```{r}
ElbowPlot(pbmc)
```


```{r}
pbmc <- FindNeighbors(pbmc, dims = 1:10)
pbmc <- FindClusters(pbmc, resolution = 0.5)
```


```{r}
# Look at cluster IDs of the first 5 cells
head(Idents(pbmc), 5)
```

```{r}
pbmc <- RunUMAP(pbmc, dims = 1:10)
```

```{r}
# note that you can set `label = TRUE` or use the LabelClusters function to help label
# individual clusters
DimPlot(pbmc, reduction = "umap")
saveRDS(pbmc, file = "pbmc_tutorial.rds")
```


```{r}
# find all markers of cluster 2
cluster2.markers <- FindMarkers(pbmc, ident.1 = 2)
head(cluster2.markers, n = 5)
```


```{r}
# find all markers distinguishing cluster 5 from clusters 0 and 3
cluster5.markers <- FindMarkers(pbmc, ident.1 = 5, ident.2 = c(0, 3))
head(cluster5.markers, n = 5)
```

```{r}
# find markers for every cluster compared to all remaining cells, report only the positive
# ones
pbmc.markers <- FindAllMarkers(pbmc, only.pos = TRUE)
pbmc.markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1)
```


```{r}
cluster0.markers <- FindMarkers(pbmc, ident.1 = 0, logfc.threshold = 0.25, test.use = "roc", only.pos = TRUE)
```


```{r, fig.width=10}
VlnPlot(pbmc, features = c("MS4A1", "CD79A"))
```

```{r, fig.width=10}
# you can plot raw counts as well
VlnPlot(pbmc, features = c("NKG7", "PF4"), slot = "counts", log = TRUE)
```

```{r, fig.width=10}
FeaturePlot(pbmc, features = c("MS4A1", "GNLY", "CD3E", "CD14", "FCER1A", "FCGR3A", "LYZ", "PPBP",
    "CD8A"))
```

```{r, fig.width=20}
pbmc.markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
    slice_head(n = 10) %>%
    ungroup() -> top10
DoHeatmap(pbmc, features = top10$gene) + NoLegend()
```

```{r}
new.cluster.ids <- c("Naive CD4 T", "CD14+ Mono", "Memory CD4 T", "B", "CD8 T", "FCGR3A+ Mono",
    "NK", "DC", "Platelet")
names(new.cluster.ids) <- levels(pbmc)
pbmc <- RenameIdents(pbmc, new.cluster.ids)
DimPlot(pbmc, reduction = "umap", label = TRUE, pt.size = 0.5) + NoLegend()
```


```{r}
library(ggplot2)
plot <- DimPlot(pbmc, reduction = "umap", label = TRUE, label.size = 4.5) + xlab("UMAP 1") + ylab("UMAP 2") +
    theme(axis.title = element_text(size = 18), legend.text = element_text(size = 18)) + guides(colour = guide_legend(override.aes = list(size = 10)))
ggsave(filename = "../output/images/pbmc3k_umap.jpg", height = 7, width = 12, plot = plot, quality = 50)
```

## Analysis CD4 and CD8 cells
```{r}
keepcells = as.integer(pbmc@active.ident) %in% c(1, 3, 5)

# Extract expression counts
counts = pbmc@assays$RNA$counts[, keepcells]
counts = as.matrix(counts)

# Extract covariate (celltype) information
clusters = as.integer(pbmc@active.ident)
clusters = clusters[clusters %in% c(1, 3, 5)]
cData = data.frame(seurat = clusters)
cData$seurat<-ifelse(cData$seurat==5, 'CD8', 'CD4')
rownames(cData) = colnames(counts)
```

```{r}
# Prepare data for Tweedieverse
input_features<-as.data.frame(t(counts))
input_metadata<-cData
names(input_metadata)<-'CellType'
input_metadata$CellType<-as.factor(input_metadata$CellType)
input_metadata$CellType<-factor(input_metadata$CellType, levels = c('CD8', 'CD4'))
```

```{r}
head(input_features[1:5, 1:5])
head(input_metadata)
```

```{r}
round(sum(input_features==0)/(nrow(input_features)*ncol(input_features))*100, 1)
```

```{r}
# we will consider top 100 most variable genes
sds<-apply(input_features, 2, function(x){sd(x, na.rm = TRUE)})
top_n_IDs<-order(sds, decreasing = TRUE)[1:100]
input_features<-input_features[, top_n_IDs]
dim(input_features)


```

### Tweedieverse
```{r}
if (!dir.exists('demo_output')) dir.create('demo_output')
PBMC_twd <- Tweedieverse(
  input_features,
  input_metadata, 
  output = 'demo_output/PBMC', # Assuming demo_output exists
  fixed_effects = c('CellType'),
  base_model = 'CPLM',
  adjust_offset = TRUE)
```

```{r}
head(PBMC_twd)
```


```{r}
table(PBMC_twd$qval<=0.05)
```

### DESeq2
```{r}
## DESeq2
dds <- DESeqDataSetFromMatrix(countData = t(input_features),
                              colData = input_metadata,
                              design= ~ CellType)
dds <- estimateSizeFactors(dds)
```

```{r}
dds <- nbinomWaldTest(dds)

res <- results(dds, contrast = c("CellType", "CD4", "CD8"))

res


```

```{r}
table(res$padj<=0.05)
```

### edgeR
```{r}
## edgeR
dge <- DGEList(counts=t(input_features), group = input_metadata$CellType)
```

```{r}
dge <- calcNormFactors(dge, method ="TMM")
dge
```

```{r}
design <- model.matrix(~CellType, data= input_metadata)
```

```{r}
dge <- estimateDisp(dge, design)
```

```{r}
fit <- glmFit(dge, design)
```

```{r}
res<- glmLRT(fit)
topC<-topTags(res, n=Inf)$table
head(topC)
```

```{r}
table(topC$FDR<=0.05)
```

### Venn plot of three methods
```{r}
TWD <- PBMC_twd[PBMC_twd$qval<=0.05, ]$feature
DESeq2 <- rownames(res[res$padj<=0.05, ])
edgeR <- rownames(topC[topC$FDR<=0.05, ])


x <- list(edgeR = edgeR, DESeq2 = DESeq2, Tweedie = TWD)
v.table <- venn(x)
```

### DE genes in all analyses
```{r}
common_genes <- Reduce(intersect, list(edgeR = edgeR, DESeq2 = DESeq2, Tweedie = TWD))

# Output the common genes
print(common_genes)
```

**DE analysis of three methods:** Tweedieverse found 82 DE genes, which is the most. edgeR found 73 and DESeq2 found 70.


```{r}
brain <- LoadData("stxBrain", type = "anterior1")


```

```{r}
brain <- SCTransform(brain, assay = "Spatial", verbose = FALSE)
brain <- NormalizeData(brain)

spe <- as.data.frame(brain@assays$SCT$counts)

filter <- filterByExpr(spe)
table(filter)

spe <- spe[filter,]

length(brain@images$anterior1@coordinates$row)

X <- list(brain@images$anterior1@coordinates$row)
Y <- list(brain@images$anterior1@coordinates$col)
coords <- data.frame(X, Y)
colnames(coords) <- c("X", "Y")


result <- nnSVG(spe, spatial_coords = coords)

```

